### ISSUE TITLE
Error using dagnn.DagNN/addLayer (line 15) - There is already a layer with name 'relu2'.

### ISSUE THREAD

**Issue by wajihullahbaig** [zhanghang1989/ResNet-Matconvnet#2]
when running the command `run_cifar_experiments([20 32 44 56 110], 'resnet');`

I get the following error.

Error using dagnn.DagNN/addLayer (line 15)
There is already a layer with name 'relu2'.

Error in res_cifar_init>add_block_res (line 175)
    net.addLayer(sprintf('relu%d', info.lastIdx), block, sprintf('sum%d', info.lastIdx), ...

Error in res_cifar_init>add_group (line 97)
  info = add_block_res(net, info, [w w info.lastNumChannel ch], stride, true, opts);

Error in res_cifar_init (line 50)
info = add_group(opts.networkType, net, n, info, 3, 16, 1, opts);

Error in res_cifar (line 42)
    net = res_cifar_init(m, 'networkType', opts.modelType, ...

Error in run_cifar_experiments (line 30)
  [net,info] = res_cifar(Ns(i), 'modelType', MTs{i}, opts);

**Comment by zhanghang1989** [comment]
Thanks for reporting the bug! 
It is fixed in the commit [#6fb8219](https://github.com/zhanghang1989/ResNet-Matconvnet/commit/f2212003107f0835f373d1e64a21452e9af25a0d)
BTW, removing ReLU layer at the end of each residual unit, we observe a small but significant improvement in test performance and the converging progress becomes smoother as described in [blog](http://zhanghang1989.github.io/ResNet/#cifar-experiments).

**Comment by wajihullahbaig** [comment]
Thanks for fixing the issue. Yes I notices that removing ReLU at the end of each residual unit does improve test performance. :)  Thanks for the wonderful code by the way! 

Cheers

**Comment by zhanghang1989** [comment]
My pleasure!
If my work is related to your research, please consider citing my [papers](http://hangzh.com/Publications.html). Thanks!

**Comment by wajihullahbaig** [comment]
The same error is also present in res_imagenet_init.m

**Comment by zhanghang1989** [comment]
Thanks for reporting the bugs!
It should be a similar issue. It will be great if you can fix it and send a push request, I will merge.
Otherwise I will fix it in two weeks, since the CVPR deadline is approaching.

**Comment by wajihullahbaig** [comment]
Ok I will do a push request in couple of days. Am not at my machine right now. Thanks for the reply.

**Comment by wajihullahbaig** [comment]
I have created the pull request. Please ignore other requests and allow the fix for the bug only.
