### ISSUE TITLE
A question on labels{fi} = fd.labels' + 1; % Index from 1

### ISSUE THREAD

**Issue by wajihullahbaig** [zhanghang1989/ResNet-Matconvnet#4]
I wanted to know why the labels are incremented by 1? in res_cifar.m
I have tried to use my own dataset. So far I have been able to run the code and because of this increment
I kept getting an error in the `vl_nnloss()` function at the line wher we have `t = - log(X(ci))` while training the net. The error was that the values held by 'ci' were exceeding the dimension of X by a value of 1. That is, X held 1280 values while ci produced an index 1281. Therefore, to remove this error I did not increment the labels by 1 and the code is running now.  Is the increment cifar10 dataset specific?

**Comment by zhanghang1989** [comment]
Hi,
I would like to fix bugs or discuss implementation detail only for my code.  However, I would not be able to help you out for the code beyond this repo. Thanks again for pointing out the bugs! Good luck for your work!

**Comment by wajihullahbaig** [comment]
Cheers :)
