### ISSUE TITLE
networkType is fixed to 'resnet'

### ISSUE THREAD

**Issue by wajihullahbaig** [zhanghang1989/ResNet-Matconvnet#5]
Hello
I think the following line in res_cifar_init.m 
`opts.networkType = 'resnet'; % 'plain' | 'resnet'`

Keeps the network type fixed even when we pass on the 'plain' network type?

`run_cifar_experiments([20 32 44 56 110 164 1001], 'plain', 'gpus', [1]);`

**Comment by zhanghang1989** [comment]
That's not true. The 'resnet' is just the default value. When we pass through the variable, it is updated. Please see [Line 17](https://github.com/zhanghang1989/ResNet-Matconvnet/blob/master/init/res_cifar_init.m#L17)

**Comment by wajihullahbaig** [comment]
Oops my bad. I missed that line! Sorry but thx for the reply :)
