### ISSUE TITLE
Error using vl_argparse (line 99) Unknown parameter 'reluafterSum'

### ISSUE THREAD

**Issue by wajihullahbaig** [zhanghang1989/ResNet-Matconvnet#6]
for the following command 
`run_cifar_experiments([20 32], 'plain','gpus',[1], 'reluaftersum',false);`I keep getting the error 

`Error using vl_argparse (line 99) Unknown parameter 'reluafterSum'`

**Comment by zhanghang1989** [comment]
You can use the following command as in the [instructions](https://github.com/zhanghang1989/ResNet-Matconvnet#train-from-scratch)

``` matlab
res_cifar(20, 'modelType', 'resnet', 'reLUafterSum', false,...
    'expDir', 'data/exp/cifar-resNOrelu-20', 'gpus', [2])
```

or you can simply add one line to [run_cifar_experiment](https://github.com/zhanghang1989/ResNet-Matconvnet/blob/master/run_cifar_experiments.m#L13)
